### ISSUE TITLE
備品詳細 Issue4 返却機能

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1B#12]
## 終了条件

自分が利用している場合は、利用申請ボタンを表示せず代わりに「返却する」を表示する
ボタンを押下すると備品が返却済みになること

**Comment by daiki-sato** [comment]
## STEP
- [ ] 「返却する」をクリックしたら、ボタンクリック時の時間をDBに入れる。
- [ ] その後、ボタンのテキストを「返却済み」にする。
