### ISSUE TITLE
検索機能 Issue1 検索ボックスによる検索

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1B#16]
## 終了条件

ヘッダー、ダッシュボードの検索ボックスに入力したキーワードと備品名の部分一致を実施し一覧画面へ遷移できること

## 前提条件

備品一覧

## 備考

検索ボックスは作成済み

**Comment by daiki-sato** [comment]
## STEP

- [ ] 検索ボックスに入力した値を送信する
- [ ] where句で、検索で入力された値に部分一致するものを取得する
- [ ] そのデータをbladeに送信する。
