### ISSUE TITLE
検索機能 Issue2 用意されたキーワードによる検索

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1B#17]
## 終了条件

検索ボックスの下に固定のキーワードが表示されていること
リンクをクリックするとクリックした文字をキーワードに検索を実施する

## 前提条件

備品一覧

**Comment by daiki-sato** [comment]
## to do
- [ ] aタグで固定文字を送れるようにする。
- [ ] controllerで送られてきた値を受け取り、それに一致するデータを取得
- [ ] bladeにデータを渡す。
