### ISSUE TITLE
ダッシュボード Issue3 もうすぐ利用可能

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1B#20]
## 終了条件

新着の下にもうすぐ利用可能な備品を最大4件表示できること
もうすぐの定義は利用中の備品の中でも終了期限3日以内の備品を指す

## 前提条件

利用申請

**Comment by daiki-sato** [comment]
## STEP

- [ ] Itemモデルで終了期限3日以内の備品を返すメソッド作成（参考：latestItems()メソッド）
- [ ] DashboardController.phpで、`$3日以内 = Item::3日以内();`を書いて、その値をbladeにわたす（copactに追記）
- [ ] bladeでcontrollerから渡されたデータを表示
- [ ] `@if(終了期限3日以内のデータがあるかを判別) `終了期限3日以内のデータがなかったら、表示しない。
