### ISSUE TITLE
マイページ Issue1 ユーザー情報変更

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1B#24]
## 終了条件

メールアドレスとお名前を入力してボタンを押下するとDBのデータが入力した情報に変更されること

## 備考

画面は作成済み

**Comment by bigdragon0610** [comment]
- [ ] 編集用のルーティング作成
- [ ] コントローラーに編集用のメソッドを追加

**Comment by daiki-sato** [comment]
![Uploading スクリーンショット 2022-09-07 10.32.47.png…]()
