### ISSUE TITLE
マイページ Issue3 自分の利用履歴一覧

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1B#26]
## 終了条件

自分が利用した履歴の一覧が表示されていること
項目は返却済み、利用期間、備品名

**Comment by bigdragon0610** [comment]
- [ ] modelにリレーションを記述
- [ ] イーガーロードしてデータをもってくる@コントローラー
- [ ] viewにデータを渡し、foreachで回して表示
