### ISSUE TITLE
備品一覧 Issue1 キーワードを入力して検索すると備品名の部分一致でヒットしたものの備品一覧を表示する

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1B#5]
## 終了条件

備品一覧の画面が作成されていること
画面に検索したキーワードと備品名の部分一致でマッチした備品のみが一覧表示されること
項目はマッチした件数、画像、カテゴリ名、備品名

## 備考

画面を新規作成

**Comment by daiki-sato** [comment]
## STEP
- [ ] blade新規作成(備品一覧)
  - [ ] 検索窓は、検索時の値を埋め込む
  - [ ] 「何件見つかりました」作成
  - [ ] 取得したデータを表示
  　　- [ ] 画像
  　　- [ ] カテゴリ名
  　　- [ ] 備品名
- [ ] controller作成(備品一覧)
- [ ] 大枠作成

----

↓は別issue
https://github.com/posse-ap/posse1-hackathon-202209-team1B/issues/18
<img width="774" alt="スクリーンショット 2022-09-08 2 25 04" src="https://user-images.githubusercontent.com/71477876/188941152-5ffc8486-aa01-4d96-b27a-d61934062a55.png">
